linters-settings:
  goimports:
    # Separate internal packages from external
    local-prefixes: github.com/volume/service/user-flight-tracking

linters:
  # Enable extra linters besides the default ones
  enable:
    - bodyclose
    - goimports
    - goconst
    - govet
    - stylecheck
    - unconvert
    - unparam
    - misspell
    - whitespace
    - errcheck